### ISSUE TITLE
bisheng

### ISSUE THREAD

**Issue by timesp** [benjycui/benjycui.github.io#4]
问题：我想使用bisheng去搭建一个类似antd官网的说明性网站，看了bisheng简单的例子，是把markdown转化为页面，有一个问题是，我怎么去使用router，使菜单具有层级性，看例子中没有合适的说明，希望能得到解答，谢谢！

**Comment by benjycui** [comment]
See: https://github.com/benjycui/bisheng/issues/17

在别人博客里乱开 issue 是不礼貌的。
