### ISSUE TITLE
the ant.design issue bot is way too aggresive and possibly buggy

### ISSUE THREAD

**Issue by aschrijver** [benjycui/benjycui.github.io#5]
Hi!

Nice project, ant.design! I believe you are the maintainer, right?

I tried filing a bug on ant.design which has bad layout on firefox android (title texts go offscreen on both sides).

Issue form is hard to fill from mobile, but worse, all my text disappeared after pressing Create leading me to an empty issue screen.

Looking at the Closed Issues I notice that other well-meaning contributors of bug reports got their issues similarly closed.

The issue bot is too aggressive, and probably has some bugs when posting.

Just saying.. but it discourages contributing :)

**Comment by benjycui** [comment]
You should file this issue in ant-design repo.

**Comment by aschrijver** [comment]
sorry i filed here! last resort to try to help.
filing on ant-design does not work from my mobile.

- fill in form. press Create
- brings you to issue screen.. text is lost!
- and filing directly is not possible

but.. never mind. sorry for disturbing.
